export const TEST = 'TEST'
export const SET_TEXT = 'SET_TEXT'
export const SET_SPEED = 'SET_SPEED'
export const SET_FONT_SIZE = 'SET_FONT_SIZE'
export const GET_ALL_SEGMENTS = 'GET_ALL_SEGMENTs'
export const REMOVE_SEGMENT = 'REMOVE_SEGMENT'
